@port = 5050
@Host =  http://localhost

@route = api/v1/users

###

POST {{Host}}:{{port}}/{{route}}/signup
Content-Type: application/json

{
    "email":"ben@ben.com",
    "password":"12341234",
    "type":"recuiter"
}

###

POST {{Host}}:{{port}}/{{route}}/login
Content-Type: application/json

{
    "email":"nena@nena.com",
    "password":"12341234"
}

