@port = 5050
@Host =  http://localhost

@route = api/v1/users

###

POST {{Host}}:{{port}}/{{route}}/signup
Content-Type: application/json

{
    "email":"john@john.com",
    "name":"john",
    "password":"12341234",
    "type":"recruiter"
}

###

POST {{Host}}:{{port}}/{{route}}/login
Content-Type: application/json

{
    "email":"john@john.com",
    "password":"12341234"
}

