@port = 5050
@Host =  http://localhost

@route = api/v1/users



@benUserToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDFiNjBlYzkwYWU5MTQ0OGY0Mzc5YiIsImlhdCI6MTYzMTcwMzIwMywiZXhwIjoxNjMyMTM1MjAzfQ.HF9jg1TtUY02Z3pjjIntHPnBiUSLHWpIqSgJLSCIwng

@recruiterToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDFiNmFiYzkwYWU5MTQ0OGY0MzdhMCIsImlhdCI6MTYzMTcwNDI0OCwiZXhwIjoxNjMyMTM2MjQ4fQ.FFEVmkoJnYDlxaGxexpKuIYkvGPm4tq5r9VsHdgJlSk
###

GET {{Host}}:{{port}}/{{route}}
Authorization: Bearer {{recruiterToken}}


###

GET {{Host}}:{{port}}/{{route}}/6141b60ec90ae91448f4379b
Authorization: Bearer {{recruiterToken}}

###
PUT {{Host}}:{{port}}/{{route}}
Content-Type: application/json
Authorization: Bearer {{recruiterToken}}

{
    "name":"nena2"
}
